//This file is automatically generated by [conv_audio.py]. Do not edit manually.
#ifndef audioAssetEnumh
#define audioAssetEnumh

enum AudioAssetName{
	_musMainMenu, 			// 0
	_musOpening, 			// 1
	_musThemeA_Battle, 			// 2
	_musThemeA_Peace, 			// 3
	_musThemeB_Battle, 			// 4
	_musThemeB_Peace, 			// 5
	_musThemeC_Battle, 			// 6
	_musThemeC_Peace, 			// 7
	_musThemeD_Battle, 			// 8
	_musThemeD_Peace, 			// 9
	_musTitle, 			// 10
	_sfxCursorMove, 			// 11
	_sfxMenuCancel, 			// 12
	_sfxMenuConfirmA, 			// 13
	_sfxMenuConfirmB, 			// 14
	_sfxMenuConfirmC, 			// 15
	_sfxMenuMove, 			// 16
	_sfxScreenPan, 			// 17
	_sfxShipDmgL, 			// 18
	_sfxShipDmgM, 			// 19
	_sfxShipDmgS, 			// 20
	_sfxShipExplodeL, 			// 21
	_sfxShipExplodeM, 			// 22
	_sfxShipExplodeS, 			// 23
	_sfxShipIdle, 			// 24
	_sfxShipMove, 			// 25
	
};

#endif