//This file is automatically generated by [conv_audio.py]. Do not edit manually.
#include "audio_engine_internal.h"

extern cu8 _12_5pulse_smp_data[];
AudioSample _12_5pulse_smp = {
	.sampleStart = _12_5pulse_smp_data, .sampleLength = 5183, .loopEnd = 5183, .loopStart = 3711, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 11025,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _25pulse_smp_data[];
AudioSample _25pulse_smp = {
	.sampleStart = _25pulse_smp_data, .sampleLength = 860, .loopEnd = 860, .loopStart = 692, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 10997,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _50pulse_smp_data[];
AudioSample _50pulse_smp = {
	.sampleStart = _50pulse_smp_data, .sampleLength = 103, .loopEnd = 101, .loopStart = 59, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 11025,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _tri_lo_smp_data[];
AudioSample _tri_lo_smp = {
	.sampleStart = _tri_lo_smp_data, .sampleLength = 1347, .loopEnd = 1347, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _tri_hi_smp_data[];
AudioSample _tri_hi_smp = {
	.sampleStart = _tri_hi_smp_data, .sampleLength = 678, .loopEnd = 678, .loopStart = 657, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _vsaw0_smp_data[];
AudioSample _vsaw0_smp = {
	.sampleStart = _vsaw0_smp_data, .sampleLength = 336, .loopEnd = 336, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _edmkick_smp_data[];
AudioSample _edmkick_smp = {
	.sampleStart = _edmkick_smp_data, .sampleLength = 5907, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 45306,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _edmsnare_smp_data[];
AudioSample _edmsnare_smp = {
	.sampleStart = _edmsnare_smp_data, .sampleLength = 8832, .loopEnd = 8832, .loopStart = 5888, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _SnareAcoustic3_smp_data[];
AudioSample _SnareAcoustic3_smp = {
	.sampleStart = _SnareAcoustic3_smp_data, .sampleLength = 5516, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 41625,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _hihat_smp_data[];
AudioSample _hihat_smp = {
	.sampleStart = _hihat_smp_data, .sampleLength = 13614, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _cym_crash_orch_smp_data[];
AudioSample _cym_crash_orch_smp = {
	.sampleStart = _cym_crash_orch_smp_data, .sampleLength = 10356, .loopEnd = 10329, .loopStart = 5462, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 5, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _fm_bass_smp_data[];
AudioSample _fm_bass_smp = {
	.sampleStart = _fm_bass_smp_data, .sampleLength = 7511, .loopEnd = 7511, .loopStart = 5299, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _FM_Bass2_smp_data[];
AudioSample _FM_Bass2_smp = {
	.sampleStart = _FM_Bass2_smp_data, .sampleLength = 4378, .loopEnd = 4378, .loopStart = 3706, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _FM_Bell1_smp_data[];
AudioSample _FM_Bell1_smp = {
	.sampleStart = _FM_Bell1_smp_data, .sampleLength = 3968, .loopEnd = 3968, .loopStart = 3799, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _FM_EPianoBell_smp_data[];
AudioSample _FM_EPianoBell_smp = {
	.sampleStart = _FM_EPianoBell_smp_data, .sampleLength = 432, .loopEnd = 432, .loopStart = 347, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44355,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _FM_Wavetable2_smp_data[];
AudioSample _FM_Wavetable2_smp = {
	.sampleStart = _FM_Wavetable2_smp_data, .sampleLength = 649, .loopEnd = 649, .loopStart = 481, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 43941,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _horn_smp_data[];
AudioSample _horn_smp = {
	.sampleStart = _horn_smp_data, .sampleLength = 3138, .loopEnd = 3138, .loopStart = 2800, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44020,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _piano_hi_smp_data[];
AudioSample _piano_hi_smp = {
	.sampleStart = _piano_hi_smp_data, .sampleLength = 16567, .loopEnd = 16567, .loopStart = 16441, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44052,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _rave_lead_smp_data[];
AudioSample _rave_lead_smp = {
	.sampleStart = _rave_lead_smp_data, .sampleLength = 25076, .loopEnd = 25076, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _string_ens_gm_smp_data[];
AudioSample _string_ens_gm_smp = {
	.sampleStart = _string_ens_gm_smp_data, .sampleLength = 28432, .loopEnd = 28354, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 31827,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _FM_Wavetable1_smp_data[];
AudioSample _FM_Wavetable1_smp = {
	.sampleStart = _FM_Wavetable1_smp_data, .sampleLength = 684, .loopEnd = 684, .loopStart = 347, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _string_ensemble2_smp_data[];
AudioSample _string_ensemble2_smp = {
	.sampleStart = _string_ensemble2_smp_data, .sampleLength = 14727, .loopEnd = 14727, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 37810,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _pipe_organ_smp_data[];
AudioSample _pipe_organ_smp = {
	.sampleStart = _pipe_organ_smp_data, .sampleLength = 18441, .loopEnd = 18073, .loopStart = 7954, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 23758,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _FM_SlapBass2_smp_data[];
AudioSample _FM_SlapBass2_smp = {
	.sampleStart = _FM_SlapBass2_smp_data, .sampleLength = 936, .loopEnd = 916, .loopStart = 244, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _power_snare_smp_data[];
AudioSample _power_snare_smp = {
	.sampleStart = _power_snare_smp_data, .sampleLength = 12962, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 20000,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _KickRockVerb_smp_data[];
AudioSample _KickRockVerb_smp = {
	.sampleStart = _KickRockVerb_smp_data, .sampleLength = 4624, .loopEnd = 4624, .loopStart = 2504, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 22050,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _FM_BassSlap_smp_data[];
AudioSample _FM_BassSlap_smp = {
	.sampleStart = _FM_BassSlap_smp_data, .sampleLength = 1232, .loopEnd = 1232, .loopStart = 556, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _psg_wt_trbass_smp_data[];
AudioSample _psg_wt_trbass_smp = {
	.sampleStart = _psg_wt_trbass_smp_data, .sampleLength = 2405, .loopEnd = 2405, .loopStart = 1731, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44020,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _whitenoisehi_smp_data[];
AudioSample _whitenoisehi_smp = {
	.sampleStart = _whitenoisehi_smp_data, .sampleLength = 104043, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _acdBassEnv1_smp_data[];
AudioSample _acdBassEnv1_smp = {
	.sampleStart = _acdBassEnv1_smp_data, .sampleLength = 1225, .loopEnd = 1225, .loopStart = 581, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _acdBassEnv2_smp_data[];
AudioSample _acdBassEnv2_smp = {
	.sampleStart = _acdBassEnv2_smp_data, .sampleLength = 1286, .loopEnd = 1286, .loopStart = 642, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _acdBassEnv3_smp_data[];
AudioSample _acdBassEnv3_smp = {
	.sampleStart = _acdBassEnv3_smp_data, .sampleLength = 1254, .loopEnd = 1254, .loopStart = 610, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _acdBassEnv4_smp_data[];
AudioSample _acdBassEnv4_smp = {
	.sampleStart = _acdBassEnv4_smp_data, .sampleLength = 917, .loopEnd = 917, .loopStart = 274, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _acdBassEnv5_smp_data[];
AudioSample _acdBassEnv5_smp = {
	.sampleStart = _acdBassEnv5_smp_data, .sampleLength = 1423, .loopEnd = 1423, .loopStart = 779, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _acdBassEnv6_smp_data[];
AudioSample _acdBassEnv6_smp = {
	.sampleStart = _acdBassEnv6_smp_data, .sampleLength = 1074, .loopEnd = 1074, .loopStart = 420, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _acdBassEnv7_smp_data[];
AudioSample _acdBassEnv7_smp = {
	.sampleStart = _acdBassEnv7_smp_data, .sampleLength = 1168, .loopEnd = 1168, .loopStart = 515, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _acdBassEnv8_smp_data[];
AudioSample _acdBassEnv8_smp = {
	.sampleStart = _acdBassEnv8_smp_data, .sampleLength = 1446, .loopEnd = 1446, .loopStart = 798, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _acdBassEnv9_smp_data[];
AudioSample _acdBassEnv9_smp = {
	.sampleStart = _acdBassEnv9_smp_data, .sampleLength = 1382, .loopEnd = 1382, .loopStart = 730, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _acdBassEnv10_smp_data[];
AudioSample _acdBassEnv10_smp = {
	.sampleStart = _acdBassEnv10_smp_data, .sampleLength = 1266, .loopEnd = 1266, .loopStart = 615, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _acdBassEnv11_smp_data[];
AudioSample _acdBassEnv11_smp = {
	.sampleStart = _acdBassEnv11_smp_data, .sampleLength = 1280, .loopEnd = 1280, .loopStart = 636, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _acdBassEnv12_smp_data[];
AudioSample _acdBassEnv12_smp = {
	.sampleStart = _acdBassEnv12_smp_data, .sampleLength = 1468, .loopEnd = 1468, .loopStart = 823, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _acdBassEnv13_smp_data[];
AudioSample _acdBassEnv13_smp = {
	.sampleStart = _acdBassEnv13_smp_data, .sampleLength = 1271, .loopEnd = 1271, .loopStart = 627, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _acdBassEnv14_smp_data[];
AudioSample _acdBassEnv14_smp = {
	.sampleStart = _acdBassEnv14_smp_data, .sampleLength = 1243, .loopEnd = 1243, .loopStart = 599, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _acdBassEnv15_smp_data[];
AudioSample _acdBassEnv15_smp = {
	.sampleStart = _acdBassEnv15_smp_data, .sampleLength = 1231, .loopEnd = 1231, .loopStart = 585, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _acdBassEnv16_smp_data[];
AudioSample _acdBassEnv16_smp = {
	.sampleStart = _acdBassEnv16_smp_data, .sampleLength = 1242, .loopEnd = 1242, .loopStart = 600, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _acdBassEnv17_smp_data[];
AudioSample _acdBassEnv17_smp = {
	.sampleStart = _acdBassEnv17_smp_data, .sampleLength = 3162, .loopEnd = 3162, .loopStart = 2502, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _alto_sax_smp_data[];
AudioSample _alto_sax_smp = {
	.sampleStart = _alto_sax_smp_data, .sampleLength = 1763, .loopEnd = 1763, .loopStart = 1580, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 47913,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _beat_loop_smp_data[];
AudioSample _beat_loop_smp = {
	.sampleStart = _beat_loop_smp_data, .sampleLength = 16858, .loopEnd = 16849, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 20000,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _flute_smp_data[];
AudioSample _flute_smp = {
	.sampleStart = _flute_smp_data, .sampleLength = 1808, .loopEnd = 1808, .loopStart = 1716, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 47655,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _glacierSynth_smp_data[];
AudioSample _glacierSynth_smp = {
	.sampleStart = _glacierSynth_smp_data, .sampleLength = 18944, .loopEnd = 18944, .loopStart = 7008, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _gpiano_c3_smp_data[];
AudioSample _gpiano_c3_smp = {
	.sampleStart = _gpiano_c3_smp_data, .sampleLength = 23407, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 10000,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _gpiano_c5_smp_data[];
AudioSample _gpiano_c5_smp = {
	.sampleStart = _gpiano_c5_smp_data, .sampleLength = 23360, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 2500,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _HipHopKick_smp_data[];
AudioSample _HipHopKick_smp = {
	.sampleStart = _HipHopKick_smp_data, .sampleLength = 11890, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _layeredLead1_smp_data[];
AudioSample _layeredLead1_smp = {
	.sampleStart = _layeredLead1_smp_data, .sampleLength = 9136, .loopEnd = 9136, .loopStart = 5120, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 47996,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _ns_sweep_smp_data[];
AudioSample _ns_sweep_smp = {
	.sampleStart = _ns_sweep_smp_data, .sampleLength = 38333, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _perc_tri_smp_data[];
AudioSample _perc_tri_smp = {
	.sampleStart = _perc_tri_smp_data, .sampleLength = 10624, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _piano_bass_smp_data[];
AudioSample _piano_bass_smp = {
	.sampleStart = _piano_bass_smp_data, .sampleLength = 13925, .loopEnd = 13925, .loopStart = 9571, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 47483,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _sampl_smp_data[];
AudioSample _sampl_smp = {
	.sampleStart = _sampl_smp_data, .sampleLength = 2131, .loopEnd = 2131, .loopStart = 1962, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44229,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _psy_bass_smp_data[];
AudioSample _psy_bass_smp = {
	.sampleStart = _psy_bass_smp_data, .sampleLength = 8432, .loopEnd = 8432, .loopStart = 7704, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _rave_lead_2_smp_data[];
AudioSample _rave_lead_2_smp = {
	.sampleStart = _rave_lead_2_smp_data, .sampleLength = 11522, .loopEnd = 11522, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _recordscratch1_smp_data[];
AudioSample _recordscratch1_smp = {
	.sampleStart = _recordscratch1_smp_data, .sampleLength = 21250, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _sine_hi_smp_data[];
AudioSample _sine_hi_smp = {
	.sampleStart = _sine_hi_smp_data, .sampleLength = 23, .loopEnd = 23, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48174,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _SnareHiphop_smp_data[];
AudioSample _SnareHiphop_smp = {
	.sampleStart = _SnareHiphop_smp_data, .sampleLength = 5456, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _spacePad_smp_data[];
AudioSample _spacePad_smp = {
	.sampleStart = _spacePad_smp_data, .sampleLength = 63392, .loopEnd = 63392, .loopStart = 43040, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _strEns3_smp_data[];
AudioSample _strEns3_smp = {
	.sampleStart = _strEns3_smp_data, .sampleLength = 9216, .loopEnd = 9216, .loopStart = 1520, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 43941,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _Syn_Bass_2_smp_data[];
AudioSample _Syn_Bass_2_smp = {
	.sampleStart = _Syn_Bass_2_smp_data, .sampleLength = 5031, .loopEnd = 5031, .loopStart = 4786, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 31942,
	.sampleType = 1, .globalVolume = 60, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _Tambourine_smp_data[];
AudioSample _Tambourine_smp = {
	.sampleStart = _Tambourine_smp_data, .sampleLength = 9712, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 0, .globalVolume = 61, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _thATransition_smp_data[];
AudioSample _thATransition_smp = {
	.sampleStart = _thATransition_smp_data, .sampleLength = 103230, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 32768,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _timpani_smp_data[];
AudioSample _timpani_smp = {
	.sampleStart = _timpani_smp_data, .sampleLength = 5032, .loopEnd = 5032, .loopStart = 2912, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 10145,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _trance_snare_smp_data[];
AudioSample _trance_snare_smp = {
	.sampleStart = _trance_snare_smp_data, .sampleLength = 9280, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _wavetable_bass_smp_data[];
AudioSample _wavetable_bass_smp = {
	.sampleStart = _wavetable_bass_smp_data, .sampleLength = 674, .loopEnd = 674, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _woodblock_smp_data[];
AudioSample _woodblock_smp = {
	.sampleStart = _woodblock_smp_data, .sampleLength = 2092, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _sfxMenuCancel_smp_data[];
AudioSample _sfxMenuCancel_smp = {
	.sampleStart = _sfxMenuCancel_smp_data, .sampleLength = 16583, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 32768,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _sfxShipMvEg_smp_data[];
AudioSample _sfxShipMvEg_smp = {
	.sampleStart = _sfxShipMvEg_smp_data, .sampleLength = 8047, .loopEnd = 8047, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 32768,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _sfxShipMvNs_smp_data[];
AudioSample _sfxShipMvNs_smp = {
	.sampleStart = _sfxShipMvNs_smp_data, .sampleLength = 61302, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 32768,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _sfxShipDmgL_smp_data[];
AudioSample _sfxShipDmgL_smp = {
	.sampleStart = _sfxShipDmgL_smp_data, .sampleLength = 28399, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 32768,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _sfxShipDmgM_smp_data[];
AudioSample _sfxShipDmgM_smp = {
	.sampleStart = _sfxShipDmgM_smp_data, .sampleLength = 27824, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 32768,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _sfxShipDmgS_smp_data[];
AudioSample _sfxShipDmgS_smp = {
	.sampleStart = _sfxShipDmgS_smp_data, .sampleLength = 15292, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 32768,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _sfxShipExplodeL_smp_data[];
AudioSample _sfxShipExplodeL_smp = {
	.sampleStart = _sfxShipExplodeL_smp_data, .sampleLength = 55644, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 32768,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _sfxShipExplodeM_smp_data[];
AudioSample _sfxShipExplodeM_smp = {
	.sampleStart = _sfxShipExplodeM_smp_data, .sampleLength = 45059, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 32768,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _sfxShipExplodeS_smp_data[];
AudioSample _sfxShipExplodeS_smp = {
	.sampleStart = _sfxShipExplodeS_smp_data, .sampleLength = 29489, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 32768,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

AudioSample *sampleList[] = {
	&_12_5pulse_smp, &_25pulse_smp, &_50pulse_smp, &_tri_lo_smp, &_tri_hi_smp, &_vsaw0_smp, &_edmkick_smp, &_edmsnare_smp, &_SnareAcoustic3_smp, &_hihat_smp, &_cym_crash_orch_smp, &_fm_bass_smp, &_FM_Bass2_smp, &_FM_Bell1_smp, &_FM_EPianoBell_smp, &_FM_Wavetable2_smp, &_horn_smp, &_piano_hi_smp, &_rave_lead_smp, &_string_ens_gm_smp, &_FM_Wavetable1_smp, &_string_ensemble2_smp, &_pipe_organ_smp, &_FM_SlapBass2_smp, &_power_snare_smp, &_KickRockVerb_smp, &_FM_BassSlap_smp, &_psg_wt_trbass_smp, &_whitenoisehi_smp, &_acdBassEnv1_smp, &_acdBassEnv2_smp, &_acdBassEnv3_smp, &_acdBassEnv4_smp, &_acdBassEnv5_smp, &_acdBassEnv6_smp, &_acdBassEnv7_smp, &_acdBassEnv8_smp, &_acdBassEnv9_smp, &_acdBassEnv10_smp, &_acdBassEnv11_smp, &_acdBassEnv12_smp, &_acdBassEnv13_smp, &_acdBassEnv14_smp, &_acdBassEnv15_smp, &_acdBassEnv16_smp, &_acdBassEnv17_smp, &_alto_sax_smp, &_beat_loop_smp, &_flute_smp, &_glacierSynth_smp, &_gpiano_c3_smp, &_gpiano_c5_smp, &_HipHopKick_smp, &_layeredLead1_smp, &_ns_sweep_smp, &_perc_tri_smp, &_piano_bass_smp, &_sampl_smp, &_psy_bass_smp, &_rave_lead_2_smp, &_recordscratch1_smp, &_sine_hi_smp, &_SnareHiphop_smp, &_spacePad_smp, &_strEns3_smp, &_Syn_Bass_2_smp, &_Tambourine_smp, &_thATransition_smp, &_timpani_smp, &_trance_snare_smp, &_wavetable_bass_smp, &_woodblock_smp, &_sfxMenuCancel_smp, &_sfxShipMvEg_smp, &_sfxShipMvNs_smp, &_sfxShipDmgL_smp, &_sfxShipDmgM_smp, &_sfxShipDmgS_smp, &_sfxShipExplodeL_smp, &_sfxShipExplodeM_smp, &_sfxShipExplodeS_smp
};

cu16 numSamples = 81;

extern AssetData _musMainMenuAsset;
extern AssetData _musOpeningAsset;
extern AssetData _musThemeA_BattleAsset;
extern AssetData _musThemeA_PeaceAsset;
extern AssetData _musThemeB_BattleAsset;
extern AssetData _musThemeB_PeaceAsset;
extern AssetData _musThemeC_BattleAsset;
extern AssetData _musThemeC_PeaceAsset;
extern AssetData _musThemeD_BattleAsset;
extern AssetData _musThemeD_PeaceAsset;
extern AssetData _musTitleAsset;
extern AssetData _sfxCursorMoveAsset;
extern AssetData _sfxMenuCancelAsset;
extern AssetData _sfxMenuConfirmAAsset;
extern AssetData _sfxMenuConfirmBAsset;
extern AssetData _sfxMenuConfirmCAsset;
extern AssetData _sfxMenuMoveAsset;
extern AssetData _sfxScreenPanAsset;
extern AssetData _sfxShipDmgLAsset;
extern AssetData _sfxShipDmgMAsset;
extern AssetData _sfxShipDmgSAsset;
extern AssetData _sfxShipExplodeLAsset;
extern AssetData _sfxShipExplodeMAsset;
extern AssetData _sfxShipExplodeSAsset;
extern AssetData _sfxShipIdleAsset;
extern AssetData _sfxShipMoveAsset;

AssetData *soundList[] = {
	&_musMainMenuAsset, &_musOpeningAsset, &_musThemeA_BattleAsset, &_musThemeA_PeaceAsset, &_musThemeB_BattleAsset, &_musThemeB_PeaceAsset, &_musThemeC_BattleAsset, &_musThemeC_PeaceAsset, &_musThemeD_BattleAsset, &_musThemeD_PeaceAsset, &_musTitleAsset, &_sfxCursorMoveAsset, &_sfxMenuCancelAsset, &_sfxMenuConfirmAAsset, &_sfxMenuConfirmBAsset, &_sfxMenuConfirmCAsset, &_sfxMenuMoveAsset, &_sfxScreenPanAsset, &_sfxShipDmgLAsset, &_sfxShipDmgMAsset, &_sfxShipDmgSAsset, &_sfxShipExplodeLAsset, &_sfxShipExplodeMAsset, &_sfxShipExplodeSAsset, &_sfxShipIdleAsset, &_sfxShipMoveAsset
};

cu16 numSounds = 26;

