//This file is automatically generated by [conv_audio.py]. Do not edit manually.
#include "audio_engine_internal.h"

extern cu8 _25pulse_smp_data[];
AudioSample _25pulse_smp = {
	.sampleStart = _25pulse_smp_data, .sampleLength = 860, .loopEnd = 860, .loopStart = 692, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 10997,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _50pulse_smp_data[];
AudioSample _50pulse_smp = {
	.sampleStart = _50pulse_smp_data, .sampleLength = 101, .loopEnd = 101, .loopStart = 59, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 11025,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _edmkick_smp_data[];
AudioSample _edmkick_smp = {
	.sampleStart = _edmkick_smp_data, .sampleLength = 5907, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 45306,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _hihat_smp_data[];
AudioSample _hihat_smp = {
	.sampleStart = _hihat_smp_data, .sampleLength = 13614, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _FM_Bass2_smp_data[];
AudioSample _FM_Bass2_smp = {
	.sampleStart = _FM_Bass2_smp_data, .sampleLength = 4378, .loopEnd = 4378, .loopStart = 3706, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _FM_EPianoBell_smp_data[];
AudioSample _FM_EPianoBell_smp = {
	.sampleStart = _FM_EPianoBell_smp_data, .sampleLength = 432, .loopEnd = 432, .loopStart = 347, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44355,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _string_ens_gm_smp_data[];
AudioSample _string_ens_gm_smp = {
	.sampleStart = _string_ens_gm_smp_data, .sampleLength = 28354, .loopEnd = 28354, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 31827,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _psg_wt_trbass_smp_data[];
AudioSample _psg_wt_trbass_smp = {
	.sampleStart = _psg_wt_trbass_smp_data, .sampleLength = 2405, .loopEnd = 2405, .loopStart = 1731, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44020,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _FM_BassSlap_smp_data[];
AudioSample _FM_BassSlap_smp = {
	.sampleStart = _FM_BassSlap_smp_data, .sampleLength = 1232, .loopEnd = 1232, .loopStart = 556, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _whitenoisehi_smp_data[];
AudioSample _whitenoisehi_smp = {
	.sampleStart = _whitenoisehi_smp_data, .sampleLength = 104043, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

AudioSample *sampleList[] = {
	&_25pulse_smp, &_50pulse_smp, &_edmkick_smp, &_hihat_smp, &_FM_Bass2_smp, &_FM_EPianoBell_smp, &_string_ens_gm_smp, &_psg_wt_trbass_smp, &_FM_BassSlap_smp, &_whitenoisehi_smp
};

cu16 numSamples = 10;

extern AssetData _musMainMenuAsset;

AssetData *soundList[] = {
	&_musMainMenuAsset
};

cu16 numSounds = 1;

